# app/models/audit_actions.py
from enum import Enum

class AuditAction(str, Enum):
    # User Authentication
    USER_LOGIN = "USER_LOGIN"
    USER_LOGIN_ATTEMPT = "USER_LOGIN_ATTEMPT"
    ADMIN_ACCESS_DENIED = "ADMIN_ACCESS_DENIED"
    ADMIN_ACCESS_GRANTED = "ADMIN_ACCESS_GRANTED" # Explicit grant log

    # User Management
    USER_LIST = "USER_LIST"
    USER_LIST_ATTEMPT = "USER_LIST_ATTEMPT"
    USER_CREATE = "USER_CREATE"
    USER_CREATE_ATTEMPT = "USER_CREATE_ATTEMPT"
    USER_DELETE = "USER_DELETE"
    USER_DELETE_ATTEMPT = "USER_DELETE_ATTEMPT"

    # Image V2 Proxy Actions (Manifest focused)
    IMAGE_PULL_MANIFEST = "IMAGE_PULL_MANIFEST"
    IMAGE_PULL_MANIFEST_ATTEMPT = "IMAGE_PULL_MANIFEST_ATTEMPT"
    IMAGE_PUSH_MANIFEST = "IMAGE_PUSH_MANIFEST"
    IMAGE_PUSH_MANIFEST_ATTEMPT = "IMAGE_PUSH_MANIFEST_ATTEMPT"
    IMAGE_MANIFEST_CHECK = "IMAGE_MANIFEST_CHECK" # Corresponds to HEAD request on manifest
    IMAGE_MANIFEST_CHECK_ATTEMPT = "IMAGE_MANIFEST_CHECK_ATTEMPT"
    # Note: IMAGE_MANIFEST_DELETE is typically initiated by management API,
    # but v2 proxy might log an attempt if a direct DELETE to manifest URL occurs.
    IMAGE_MANIFEST_DELETE_VIA_PROXY_ATTEMPT = "IMAGE_MANIFEST_DELETE_VIA_PROXY_ATTEMPT"


    # Image Management API (More specific actions)
    IMAGE_TAGS_LIST = "IMAGE_TAGS_LIST"
    IMAGE_TAGS_LIST_ATTEMPT = "IMAGE_TAGS_LIST_ATTEMPT"
    IMAGE_CATALOG_LIST = "IMAGE_CATALOG_LIST"
    IMAGE_CATALOG_LIST_ATTEMPT = "IMAGE_CATALOG_LIST_ATTEMPT"
    IMAGE_REPO_DELETE = "IMAGE_REPO_DELETE" # Deleting all manifests in a repository
    IMAGE_REPO_DELETE_ATTEMPT = "IMAGE_REPO_DELETE_ATTEMPT"
    IMAGE_TAG_DELETE = "IMAGE_TAG_DELETE" # Deleting a specific tag (manifest)
    IMAGE_TAG_DELETE_ATTEMPT = "IMAGE_TAG_DELETE_ATTEMPT"

    # Audit Log Access
    AUDIT_LOG_VIEW = "AUDIT_LOG_VIEW"
    AUDIT_LOG_VIEW_ATTEMPT = "AUDIT_LOG_VIEW_ATTEMPT" # If there was an error before returning logs

    # System/Configuration Errors (example)
    SYSTEM_HTPASSWD_UNAVAILABLE = "SYSTEM_HTPASSWD_UNAVAILABLE"
    SYSTEM_BACKEND_REGISTRY_ERROR = "SYSTEM_BACKEND_REGISTRY_ERROR"